language: node_js
node_js:
    - "0.10"
before_install:
    - gem install sass
    - gem install compass
    - npm install -g typescript
    - npm install -g grunt-cli
    - npm install -g testem
    - npm install
notifications:
    email: false
